name: Hugo Serve
on:
  push:
    branches:
      - master

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hugo server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          command: |
            cd app/
            git checkout master
            git reset --hard origin/master
            git pull
            chmod +x deploy/server-stop.sh && ./deploy/server-stop.sh
            chmod +x deploy/server-start.sh && ./deploy/server-start.sh